### ISSUE TITLE
Toast left aligned

### ISSUE THREAD

**Issue by adnaanbheda** [arnnis/react-native-fast-toast#1]
I'm facing a tiny problem. The toasts are left aligned and not centered in the screen as you can see.

 I think by default they should be centered right ?

![toast](https://user-images.githubusercontent.com/25040547/92655331-d95c0680-f30e-11ea-8e8b-acbeb0bae3a5.jpeg)

**Comment by fluxroom-git** [comment]
i have the same issue

**Comment by arnnis** [comment]
Yes that's weird
What platform are you on? and which react-native version

**Comment by fluxroom-git** [comment]
i'm having the same issue

**Comment by fluxroom-git** [comment]
react-native: 0.63.2
macOS
testing on IOS

**Comment by arnnis** [comment]
I just published a new release (v1.0.5). please confirm if the it's working properly now.

**Comment by adnaanbheda** [comment]
@arnnis fixed ! working fine now.
