### ISSUE TITLE
`placement` not working when using the hook

### ISSUE THREAD

**Issue by spsaucier-bakkt** [arnnis/react-native-fast-toast#10]
The `placement` property doesn't seem to be working properly in the context of `toast.show()`. The toast message just shows up on the bottom as usual.

The [`ToastOptions`](
https://github.com/arnnis/react-native-fast-toast/blob/800c1504edbc402a5fc2f19e5374b76ebe81ceac/src/toast.tsx#L13) interface doesn't include it, and while both `ToastProps` do, it seems that `placement` is not intended to be a property of the `show` method, i.e.:
```
toast.show('text', {placement: 'top'})
```

**Comment by arnnis** [comment]
Hi.
Yes it was not intended to be an option for `show`.
I've forgot to add these Toast props to `ToastProvider` in the recent release. thanks for report!

**Comment by arnnis** [comment]
I just released [v1.1.2](https://github.com/arnnis/react-native-fast-toast/releases/tag/v1.1.2)

`Toast` props (placement, offset) now can be used in ToastProvider too. like this:
`
<ToastProvider placement="top" offset={50} />
`

**Comment by chichke** [comment]
Still having the same issue

**Comment by arnnis** [comment]
Hi.
the placement option is not intended to be a property of the show method. it needs to be on the component itself.
like this:
```<Toast placement="top" />```

or if you use hooks

```<ToastProvider placement="top">```

**Comment by chichke** [comment]
Thanks for your answer, nice library tho

**Comment by arnnis** [comment]
Starting from version 3, now you can use placement in show method too.  full changelog [here](https://github.com/arnnis/react-native-fast-toast/releases/tag/v3.0.0)
