### ISSUE TITLE
Rendering multiple toast

### ISSUE THREAD

**Issue by Svarto** [arnnis/react-native-fast-toast#4]
Great job with this library, I really like it. I am struggling to make the toasts build as you have in the gif example so that you can have multiple toasts showing at one time. i.e. the onPress button is clicked multiple times and each click creates a new toast, for each new toast it is rendered above the old one (or the old one is pushed up to make space for the new one).

When I try to render more than one toast, I get a red error: 

"Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state."

How did you do it on the gif in the readme? e.g. you click on "normal" toast several times and several toasts are shown at once.

**Comment by Svarto** [comment]
I guess to specify, it is not possible to render more than one toast at the same time. Sequentially it is possible, but when trying to render more than one at the same time - you get the above warning.

**Comment by arnnis** [comment]
Hey thanks for using the library

Have you checked the example app? it's code of the gif in readme

Can you post the code you are running? also the platform and react-native version you are testing on

**Comment by Svarto** [comment]
I figured it out, so if you call several toasts at once then you receive the error, i.e. I had a global toast and called it like this:

toast.show("test1", {type: "success"})
toast.show("test2", {type: "danger"})

This does not work as the second toast gets called while the first one is in transition animation. However, just doing a small delay makes them correct stack on top of eachother, i.e.

toast.show("test1", {type: "success"});
setTimeout(() => toast.show("test2", {type: "danger"}), 10);

Thanks for the quick reply!!

**Comment by arnnis** [comment]
I just published a new version with a possible fix for this. 
please confirm if it's working now without your setTimeout
