### ISSUE TITLE
Swipe to close support

### ISSUE THREAD

**Issue by mthines** [arnnis/react-native-fast-toast#49]
Hey.

Do you have any plans for supporting swipe to close?

**Comment by arnnis** [comment]
Yes I think that's a nice feature. But it's a bit hard to implement. Will work on it when find some time.
Contributons are welcome too.

**Comment by arnnis** [comment]
Swipe to close feature is now supported in [Version 3](https://github.com/arnnis/react-native-fast-toast/releases/tag/v3.0.0). 
let me know if you have any feedbacks.
