### ISSUE TITLE
Property 'toast' does not exist on type 'Global & typeof globalThis'.

### ISSUE THREAD

**Issue by Mozartuss** [arnnis/react-native-fast-toast#5]
Nice work, 

I use React-Native with TypeScript and I define the toast globally on `App.tsx` like this:

```typescript
<Provider store={store}>
  <NavigationContainer>
    <Stack.Navigator>
           //....
    </Stack.Navigator>
  </NavigationContainer>
  <Toast ref={(ref) => global["toast"] = ref} placement={"top"} />
</Provider>
```

And I get the Warning:

> TS7053: Element implicitly has an 'any' type because expression of type '"toast"' can't be used to index type 'Global & typeof globalThis'.   Property 'toast' does not exist on type 'Global & typeof globalThis'.

How can I fix this? 
Thanks in advance.

**Comment by arnnis** [comment]
Hi

You have to add a index.d.ts to your project root to add toast to your global interface.

Check global example in Readme.

**Comment by arnnis** [comment]
if you still have problem or have suggestion please feel free to reopen the issue

**Comment by yleclanche** [comment]
Not ideal, but you can use : 
`<Toast ref={(ref) => ((global as any)["toast"] = ref)} />`

Same thing to call the function : 
`(global as any)["toast"].show("Task finished successfully", { type: "success" })`

**Comment by arnnis** [comment]
Hi. 
This error can be fixed by adding an index.d.ts to your project root.
Check [example app](https://github.com/arnnis/react-native-fast-toast/blob/master/example/index.d.ts)

Or alternatively you can use hooks.
