### ISSUE TITLE
add normalColor prop

### ISSUE THREAD

**Issue by ezekiel747** [arnnis/react-native-fast-toast#51]
Hi, 
I wanted to change the color for the "normal" type and added style={{ backgroundColor: 'gray' }} to it.
But now if using other types ("danger" for example) the background is still gray - at least when using it on the react native web platform.

Could you please add a "normalColor" prop?
Or is there any other way around this?

Thanks! And great lib, btw!

**Comment by arnnis** [comment]
Hi. 

Thanks for opening issue.

This is now fixed in the new version, Now with `normalColor` you change normal toasts color, Please confirm it's working.

**Comment by ezekiel747** [comment]
Thank you very much, i tested the new version 2.3.0 and can confirm it works as expected.
One small suggestion - please add this new prop to the examples in the readme file as well, so people know about it right from the start. 

Quick response, great job!
