### ISSUE TITLE
Is there is a way to close a toast when clicked ?

### ISSUE THREAD

**Issue by karelnet** [arnnis/react-native-fast-toast#7]
Great job, smooth and easy to implement.

I couldn't find a way to close a toast when clicked. Any suggestion ?

**Comment by arnnis** [comment]
I just published a new release. [v1.0.9](https://github.com/arnnis/react-native-fast-toast/releases/tag/v1.0.9)

You can do this now: 

```
toast.show("Press to close", {
  onPress: id => toast.hide(id)
});
```

**Comment by arnnis** [comment]
I'm closing this issue, if you still have problem let me know

**Comment by karelnet** [comment]
Sorry, I wasn't available these days. Thank you for your quick reply. It didn't work for me. I updated to this new version and tried out but click doesn't seem to work : when I click, it's the zone below the toast message that is triggered. 
PS : RN 0.63 / expo / react-navigation 4

**Comment by arnnis** [comment]
I can not seem to reproduce this issue. 
Please check example app in repo. there is an example for this.

**Comment by karelnet** [comment]
I confirm your example is working. Don't know why it doesn't work in my app. I'll try to investigate.

**Comment by spsaucier-bakkt** [comment]
It's working properly for me too.
