### ISSUE TITLE
improve useToast.d.ts

### ISSUE THREAD

**Issue by 0x0a0d** [arnnis/react-native-fast-toast#74]
`const toast = useToast()` should export only 3 methods: `show, update, hide`
```d.ts
import * as React from 'react'
import ToastContainer from '../toast-container'

export default function useToast(): Pick<ToastContainer, 'show'| 'update'| 'hide'>
```
Look better
![image](https://user-images.githubusercontent.com/32500015/122489564-2a212e00-d00a-11eb-812f-fa2bdcd884d5.png)

**Comment by 0x0a0d** [comment]
![image](https://user-images.githubusercontent.com/32500015/122489531-1b3a7b80-d00a-11eb-8fd9-483c316d2e6b.png)

**Comment by arnnis** [comment]
Hi. This sounds like a good idea.

I just published in the new version with this change. You should only the three main methods now.
