### ISSUE TITLE
Use React context to share ref

### ISSUE THREAD

**Issue by nandorojo** [arnnis/react-native-fast-toast#8]
Hey, I like the library, thanks for open sourcing. Have you considered using `createContext` with a provider to put the ref at the root of the app, and then a `useToast` hook? I think it would be better than using `global.toast`, since it stays more in the react world.

**Comment by arnnis** [comment]
Hi, 
Yes I've thought about. I personally prefer the global way because it works in redux actions too.
but I'll try using context as an optional way of using the library.

**Comment by arnnis** [comment]
I just published a [new release ](https://github.com/arnnis/react-native-fast-toast/releases/tag/v1.1.0)with hook support, now you can do this:

In index.js or App.js:
```
import { ToastProvider } from 'react-native-fast-toast'

const App = () => {
  return (
    <ToastProvider>
      <RestOfApp />
    </ToastProvider>
  )
}
```

Then use hook like this:
```
import { useToast } from 'react-native-fast-toast'

const Component = () => {
  const toast = useToast()
}
```

I'll update readme soon

**Comment by nandorojo** [comment]
Thank you!
