### ISSUE TITLE
Placement "top" has no effect on ToastProvider

### ISSUE THREAD

**Issue by wkirby** [arnnis/react-native-fast-toast#82]
### Current behaviour

When using the `placement="top"` param on the `ToastProvider`, toast messages still default to `bottom` placement.

### Expected behaviour

When using the `placement="top"` param on the `ToastProvider`, toast messages should default to `top` placement.

### Code sample

For Syntax Highlighting check this [link](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

```
const App = () =>
  <ToastProvider placement="top">
      <MyComponent />
  </ToastProvider>

const MyComponent = () => {
  const toast = useToast();

  useEffect(() => {
    toast.show("Hello from top");
  }, []);
  
  return <Text>Hello World</Text>;
}
```

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios               | iOS 14
| react-native                 | `0.64.2`
| react-native-fast-toast      | `^3.0.0`
| node                         | 
| npm                  |

**Comment by wkirby** [comment]
I believe the answer here is very straightforward. The `show` method does not look at the `ToastContainer` props:

Current code:

```ts
show = (message: string | JSX.Element, toastOptions?: ToastOptions) => {
    let id = toastOptions?.id || Math.random().toString();
    const onClose = () => this.hide(id);

    requestAnimationFrame(() => {
      this.setState({ toasts: this.state.toasts.filter((t) => t.id !== id) });
      this.setState({
        toasts: [
          {
            id,
            onClose,
            message,
            ...toastOptions,
          },
          ...this.state.toasts,
        ],
      });
    });

    return id;
  };
```

Adding something like:

```
placement = toastOptions?.placement || this.props.placement;

...

{
  id,
  placement,
  ...toastOptions
}
```

Should, I think, do the trick.

**Comment by arnnis** [comment]
Hi 
Thanks for detailed report. I just released a fix for this issue. please confirm if it's working now

**Comment by wkirby** [comment]
Thanks for the very fast turnaround! I can confirm that `3.0.1` fixes this issue in my project.
