### ISSUE TITLE
Toast renders under keyboard

### ISSUE THREAD

**Issue by lukeramsden** [arnnis/react-native-fast-toast#9]
### Current behaviour

I'm showing an error toast while the keyboard is open, and it renders below the keyboard.
This is on iOS, and I haven't tested Android (yet, I will).

### Expected behaviour

The toast's bottom offset should adjust to the keyboard height so it is visible when shown.

### Code sample

If necessary I will make one, I am just busy for the rest of today.

### Screenshots (if applicable)

https://streamable.com/0yge8f

### What have you tried

I have not tried any manual workarounds yet, but my initial thought would be to use react-native-keyboard-height, and pass the keyboard height to the bottom offset at the callsite. However, if the keyboard was to close while the toast is showing, it would not move, so it's not an ideal solution.

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | ios12
| react-native                 | 0.63.3
| react-native-fast-toast      | 1.1.0
| node                         | 10
| npm or yarn                  | 1.22.5

---

If a code sample is necessary I will provide one as soon as I get the chance, I'm just busy for the rest of today. I will edit this as and when I do that.
I could also probably make a PR to fix this myself.

**Comment by arnnis** [comment]
Hi. Thanks for detailed report. I tested this on android, it's working properly there.
I don't have access to a mac right now to test IOS.

have you tried wrapping Toast component into a [KeyboardAvoidingView](https://reactnative.dev/docs/keyboardavoidingview)?

**Comment by lukeramsden** [comment]
I did suspect that android would work as it handles keyboard spacing differently. I’ll look in to it.On Mon, Oct 5, 2020 at 17:33, Alireza Rezania <notifications@github.com> wrote:  
Hi. Thanks for detailed report. I tested this on android, it's working properly there.
I don't have access to a mac right now to test IOS.
have you tried wrapping Toast component into a KeyboardAvoidingView?

**Comment by arnnis** [comment]
I think implementing this in library is better because the default ToastProvider can not be workarounded like this. A PR would be great. (this repo is hackoctoberfest ready btw :D)
